# fly.toml app configuration file generated for key-manager on 2023-06-30T19:59:18+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "key-manager"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
